name: Build and Release Hugo Site

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: sampletodobackend
  WORKING_DIRECTORY: homepage

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.73.0'

      - name: Build hugo
      - run: hugo --minify --baseURL https://offering.solutions/

      - name: 'Copy Files to: homepage/public/dist-cdn'
      - run: Copy-Item -Path js/*,css/*,fonts/*,img/*,index.json -Destination dist-cdn -recurse
        working-directory: public

      - name: 'Copy Files to: homepage/public/dist-blog'
      - run: |
          Copy-Item -Path blog/* -Destination dist-blog/blog -recurse
          Copy-Item -Path categories/* -Destination dist-blog/categories -recurse
          Copy-Item -Path tags/* -Destination dist-blog/tags -recurse
          Copy-Item -Path talks/* -Destination dist-blog/talks -recurse
          Copy-Item -Path newsletter/* -Destination dist-blog/newsletter -recurse
        working-directory: public

      - name: 'Copy Files to: homepage/public/dist-blog'
      - run: |
          New-Item -Path public/dist-blog -ItemType Directory
          Copy-Item -Path public/*.* -Destination public/dist-blog

      # - name: 'Copy Files to: homepage/public/dist-blog'
      #   run: |
      #     Copy 'homepage/public/blog\**\*.*
      #     categories\**\*.*
      #     tags\**\*.*
      #     talks\**\*.*
      #     newsletter\**\*.*
      #     *.*' 'homepage/public/dist-blog'

      # - name: 'Publish Artifact: blog'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: homepage/public/dist-blog
      #     name: blog

      # - name: 'Publish Artifact: cdn'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: homepage/public/dist-cdn
      #     name: cdn
